// FR-13 keybinding registry (architecture.md §5.6) + the canonical combo
// string format shared by every rebindable action, so a captured
// KeyboardEvent and a stored combo string are always compared the same way
// (closes the case/format-sensitivity gap flagged in this session's backend
// code review — combos are always generated by `formatCombo`, never
// hand-typed, so two equivalent bindings can't drift into different casing).

export type ActionId =
	| "clipboard.copy"
	| "clipboard.paste"
	| "pane.splitBottom"
	| "pane.splitRight"
	| "pane.moveFocusLeft"
	| "pane.moveFocusRight"
	| "pane.moveFocusUp"
	| "pane.moveFocusDown"
	| "terminal.zoomIn"
	| "terminal.zoomOut"
	| "terminal.closeSession"
	| "terminal.nextTab"
	| "terminal.previousTab"
	| "sidebar.toggle";

export interface KeybindingActionDef {
	id: ActionId;
	label: string;
	group: "Clipboard" | "Panes" | "Terminal" | "Tabs" | "Sidebar";
}

/** The 14-action registry (architecture.md §5.6) — order here is the order
 * rows render in the Settings panel (components.md, Keybinding Row /
 * Settings Panel pattern). */
export const KEYBINDING_ACTIONS: KeybindingActionDef[] = [
	{ id: "clipboard.copy", label: "Copy selection", group: "Clipboard" },
	{ id: "clipboard.paste", label: "Paste", group: "Clipboard" },
	{ id: "pane.splitBottom", label: "Split pane down", group: "Panes" },
	{ id: "pane.splitRight", label: "Split pane right", group: "Panes" },
	{ id: "pane.moveFocusLeft", label: "Move focus left", group: "Panes" },
	{ id: "pane.moveFocusRight", label: "Move focus right", group: "Panes" },
	{ id: "pane.moveFocusUp", label: "Move focus up", group: "Panes" },
	{ id: "pane.moveFocusDown", label: "Move focus down", group: "Panes" },
	{ id: "terminal.zoomIn", label: "Zoom in", group: "Terminal" },
	{ id: "terminal.zoomOut", label: "Zoom out", group: "Terminal" },
	{ id: "terminal.closeSession", label: "Close terminal", group: "Terminal" },
	{ id: "terminal.nextTab", label: "Next tab", group: "Tabs" },
	{ id: "terminal.previousTab", label: "Previous tab", group: "Tabs" },
	{ id: "sidebar.toggle", label: "Show/hide sidebar", group: "Sidebar" },
];

export function actionLabel(id: string): string {
	return KEYBINDING_ACTIONS.find((a) => a.id === id)?.label ?? id;
}

/** Mirrors settings_store's own defaults (architecture.md §5.6) — used as
 * this store's initial state so components (e.g. TerminalPane's clipboard
 * shortcuts) work correctly even in the brief window before the real
 * `getSettings()` response arrives, not just after. */
export const DEFAULT_KEYBINDINGS: Record<ActionId, string> = {
	"clipboard.copy": "Ctrl+Shift+C",
	"clipboard.paste": "Ctrl+Shift+V",
	"pane.splitBottom": "Alt+Shift+D",
	"pane.splitRight": "Alt+Shift+R",
	"pane.moveFocusLeft": "Alt+ArrowLeft",
	"pane.moveFocusRight": "Alt+ArrowRight",
	"pane.moveFocusUp": "Alt+ArrowUp",
	"pane.moveFocusDown": "Alt+ArrowDown",
	"terminal.zoomIn": "Ctrl+=",
	"terminal.zoomOut": "Ctrl+-",
	// Closes the *focused pane*, not the whole tab — and the tab goes with it
	// only when that was its last pane (`closePane`'s own rule). Matches
	// Tilix/Terminator, whose Ctrl+Shift+W this deliberately mirrors.
	"terminal.closeSession": "Ctrl+Shift+W",
	"terminal.nextTab": "Ctrl+Tab",
	"terminal.previousTab": "Ctrl+Shift+Tab",
	"sidebar.toggle": "Ctrl+B",
};

/** Physical-key based (like the app's existing Ctrl+Shift+C/V checks used
 * `event.code`, not `event.key`) — layout-independent, and stable across
 * keyboard layouts the way a "which letter did you type" check wouldn't be. */
function codeToKeyName(code: string): string {
	if (code.startsWith("Key")) return code.slice("Key".length); // "KeyC" -> "C"
	if (code.startsWith("Digit")) return code.slice("Digit".length); // "Digit1" -> "1"
	// "Equal"/"Minus" are the physical-key codes for "="/"-" (DEFAULT_KEYBINDINGS'
	// terminal.zoomIn/zoomOut use "Ctrl+="/"Ctrl+-" — without this mapping,
	// pressing that physical key would format as "Ctrl+Equal"/"Ctrl+Minus" and
	// never match those defaults at all).
	if (code === "Equal") return "=";
	if (code === "Minus") return "-";
	return code; // "ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown", etc. already fine
}

/** Canonical "Ctrl+Shift+C" / "Alt+ArrowLeft" style string for a KeyboardEvent
 * — modifier order is always Ctrl, Alt, Shift, Cmd, matching architecture.md
 * §5.6's registry table exactly (e.g. "Alt+Shift+D", not "Shift+Alt+D"). */
export function formatCombo(event: KeyboardEvent): string {
	const parts: string[] = [];
	if (event.ctrlKey) parts.push("Ctrl");
	if (event.altKey) parts.push("Alt");
	if (event.shiftKey) parts.push("Shift");
	if (event.metaKey) parts.push("Cmd");
	parts.push(codeToKeyName(event.code));
	return parts.join("+");
}

/** components.md, Keybinding Row — Do/Don't: a captured combo must include
 * Ctrl, Alt, or Cmd, or an unmodified letter key would fire on every normal
 * keystroke typed into the terminal. Shift alone does not count. */
export function hasRequiredModifier(event: KeyboardEvent): boolean {
	return event.ctrlKey || event.altKey || event.metaKey;
}

export function matchesCombo(event: KeyboardEvent, combo: string | undefined): boolean {
	if (!combo) return false;
	return formatCombo(event) === combo;
}
